name: flutter_app123
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui系
  splashscreen: ^1.2.0
  webview_flutter: ^0.3.19+5
  camera: ^0.5.7+3
  fluttertoast: ^3.1.3

  # logic系
  http: ^0.12.0+4

  shared_preferences: ^0.5.6+1

  # Date
  intl: ^0.16.1

  sqflite: ^1.2.0
  path_provider: ^1.5.1

  firebase_core: ^0.4.4
  firebase_analytics: ^5.0.11
  cloud_firestore: ^0.13.2+1
  firebase_messaging: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets:
    - assets/